### ISSUE TITLE
Error when zooming using ZoomPdfView 

### ISSUE THREAD

**Issue by ariq-d** [alpha0010/react-native-pdf-viewer#21]
Hi,
I'm trying to display a zoomable PDF file, I tried using <ZoomPdfView /> and the page is displayed, but this error shows up when trying pinch to zoom in. Any idea why this can happen and how to solve?

![1725613262280](https://github.com/user-attachments/assets/b81e8663-70cd-42eb-963a-971dfa2d5786)

Here is the code snippet:

```javascript
const PdfViewer = ({ navigation }) => {

  const pdfRef = useRef();

  const uri = navigation.state.params.uri;
  const pageTitle = navigation.state.params.title;
  const initialPage = navigation?.state?.params?.initialPage;

  const sourceFile = useMemo(() => `${RNFS.DocumentDirectoryPath}/PDF-FILE.pdf`, []);

  const [isLoading, setIsLoading] = useState(true);
  const [localFilePath, setLocalFilePath] = useState(null);

  const onBackPressed = useCallback(() => {
    navigation.goBack();
  }, [navigation]);

  const renderLoadingIndicator = useMemo(() => (
    <View style={styles.loadingContainer}>
      <ActivityIndicator size='small' style={styles.activityIndicator} />
    </View>
  ), []);

  const onPdfLoadComplete = useCallback(() => {
    setIsLoading(false);
  }, [initialPage]);

  const downloadPdf = useCallback(async () => {
    try {
      const downloadResult = await RNFS.downloadFile({
        fromUrl: uri,
        toFile: sourceFile,
      }).promise;
      if (downloadResult.statusCode === 200) {
        setLocalFilePath(sourceFile);
      }
    } catch (error) {
      return Promise.resolve();
    }
  }, [uri, sourceFile]);

  useEffect(() => {
    downloadPdf();
  }, []);

  return (
    <SafeAreaView style={styles.safeAreaContainer}>
      <Navbar
        title={pageTitle}
        titleAlign='left'
        tintColor='black'
        backgroundColor='transparent'
        onPressBack={onBackPressed}
        compact
      />
      <View style={styles.container}>
        <ZoomPdfView
          ref={pdfRef}
          page={initialPage - 1}
          source={`file://${localFilePath}`}
          onLoadComplete={onPdfLoadComplete}
          trustAllCerts={Platform.OS === 'ios'}
          style={styles.pdfContainer}
        />
        {isLoading && renderLoadingIndicator}
      </View>
    </SafeAreaView>
  );
};

export default React.memo(PdfViewer);
```

Here are (some of) the libraries installed:
```
"react-native": "0.72.6",
"react-native-pdf-light": "^2.4.0",
"react-native-reanimated": "3.6.2",
"react-native-gesture-handler": "^2.13.4",
```

In the future I want to display all pages in ScrollView, so that the user can scroll through the entire PDF and zoom each page.

Any help would be much appreciated,
thanks in advance.

**Comment by hipolitoluc** [comment]
Hi
app crashes when trying to pinch zoom in with the below error
```

          Fatal Exception: java.util.ConcurrentModificationException:
       at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:1029)
       at java.util.ArrayList$Itr.next(ArrayList.java:982)
       at com.swmansion.gesturehandler.core.GestureHandlerOrchestrator.onHandlerStateChange(GestureHandlerOrchestrator.kt:105)
       at com.swmansion.gesturehandler.core.GestureHandler.moveToState(GestureHandler.kt:558)
       at com.swmansion.gesturehandler.core.GestureHandler.fail(GestureHandler.kt:653)
       at com.swmansion.gesturehandler.core.PinchGestureHandler.onHandle(PinchGestureHandler.kt:80)
       at com.swmansion.gesturehandler.core.GestureHandler.handle(GestureHandler.kt:380)
       at com.swmansion.gesturehandler.core.GestureHandlerOrchestrator.deliverEventToGestureHandler(GestureHandlerOrchestrator.kt:255)
       at com.swmansion.gesturehandler.core.GestureHandlerOrchestrator.deliverEventToGestureHandlers(GestureHandlerOrchestrator.kt:211)
       at com.swmansion.gesturehandler.core.GestureHandlerOrchestrator.onTouchEvent(GestureHandlerOrchestrator.kt:41)
       at com.swmansion.gesturehandler.react.RNGestureHandlerRootHelper.dispatchTouchEvent(RNGestureHandlerRootHelper.kt:101)
       at com.swmansion.gesturehandler.react.RNGestureHandlerRootView.dispatchTouchEvent(RNGestureHandlerRootView.kt:36)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3328)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2998)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3328)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2998)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3328)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2998)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3328)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2998)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3328)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2998)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3328)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2998)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3328)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2998)
       at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:776)
       at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1967)
       at android.app.Activity.dispatchTouchEvent(Activity.java:4548)
       at androidx.appcompat.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:70)
       at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:734)
       at android.view.View.dispatchPointerEvent(View.java:16489)
       at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:8602)
       at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:8353)
       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:7682)
       at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:7739)
       at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:7705)
       at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:7908)
       at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:7713)
       at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:7965)
       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:7686)
       at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:7739)
       at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:7705)
       at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:7713)
       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:7686)
       at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:11250)
       at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:11119)
       at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:11075)
       at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:11384)
       at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:337)
       at android.os.MessageQueue.nativePollOnce(MessageQueue.java)
       at android.os.MessageQueue.next(MessageQueue.java:335)
       at android.os.Looper.loopOnce(Looper.java:187)
       at android.os.Looper.loop(Looper.java:319)
       at android.app.ActivityThread.main(ActivityThread.java:8919)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:578)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)
```
although it works when ZoomPdfView is wrapped with scrollview but the pinch in behaviour is not proper.
